spring.application.name=batch
spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.validate-transaction-state=true
spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost/mydatabase